"""initial_schema

Revision ID: bf7738a16f18
Revises: 
Create Date: 2026-05-11 22:16:13.942867

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf7738a16f18'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pg_trgm is required for the GIN trigram index on hostnames.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fingerprint_sha256', sa.Text(), nullable=False),
    sa.Column('spki_sha256', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.Text(), nullable=False),
    sa.Column('issuer_dn', sa.Text(), nullable=False),
    sa.Column('issuer_common_name', sa.Text(), nullable=True),
    sa.Column('issuer_organization', sa.Text(), nullable=True),
    sa.Column('subject_dn', sa.Text(), nullable=False),
    sa.Column('subject_common_name', sa.Text(), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_algorithm_oid', sa.Text(), nullable=False),
    sa.Column('signature_algorithm_name', sa.Text(), nullable=False),
    sa.Column('public_key_algorithm_oid', sa.Text(), nullable=False),
    sa.Column('public_key_algorithm_name', sa.Text(), nullable=False),
    sa.Column('public_key_bits_or_curve', sa.Text(), nullable=True),
    sa.Column('is_precertificate', sa.Boolean(), nullable=False),
    sa.Column('is_wildcard_present', sa.Boolean(), nullable=False),
    sa.Column('san_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_key_der', sa.LargeBinary(), nullable=True),
    sa.Column('raw_der', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('fingerprint_sha256', name='uq_certificates_fingerprint_sha256')
    )
    op.create_table('ct_db_contention_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scope', sa.Text(), server_default=sa.text("'global'"), nullable=False),
    sa.Column('pressure_ema', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('extra_sleep_seconds', sa.Numeric(precision=12, scale=3), server_default=sa.text('0'), nullable=False),
    sa.Column('batch_size_cap', sa.Integer(), nullable=True),
    sa.Column('healthy_streak', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_retryable_errors', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('retry_window_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retry_window_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_db_contention_state')),
    sa.UniqueConstraint('scope', name=op.f('uq_ct_db_contention_state_scope'))
    )
    op.create_table('ct_instance_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('storage_profile', sa.Text(), nullable=False),
    sa.Column('cert_storage_mode', sa.Text(), nullable=False),
    sa.Column('hostname_retention_mode', sa.Text(), nullable=False),
    sa.Column('backfill_days', sa.Integer(), nullable=False),
    sa.Column('cert_retention_days', sa.Integer(), nullable=False),
    sa.Column('observation_retention_days', sa.Integer(), nullable=False),
    sa.Column('entry_outcome_retention_days', sa.Integer(), nullable=False),
    sa.Column('metrics_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('settings_hash', sa.Text(), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_instance_settings'))
    )
    op.create_table('ct_log_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_id_b64', sa.Text(), nullable=False),
    sa.Column('operator_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('public_key_b64', sa.Text(), nullable=False),
    sa.Column('log_state', sa.Text(), nullable=False),
    sa.Column('temporal_shard_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_shard_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_eligible_for_tail', sa.Boolean(), nullable=False),
    sa.Column('is_eligible_for_backfill', sa.Boolean(), nullable=False),
    sa.Column('source_list', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_sources')),
    sa.UniqueConstraint('log_id_b64', name='uq_ct_log_sources_log_id_b64'),
    sa.UniqueConstraint('url', name='uq_ct_log_sources_url')
    )
    op.create_table('ct_maintenance_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_type', sa.Text(), server_default=sa.text("'prune_for_storage_profile'"), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('storage_profile', sa.Text(), nullable=True),
    sa.Column('settings_hash', sa.Text(), nullable=True),
    sa.Column('deleted_certificates', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_certificate_hostnames', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_observations', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_entry_outcomes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_ingestion_metrics', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('preserved_hostnames', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("mode IN ('dry_run', 'execute')", name=op.f('ck_ct_maintenance_runs_ck_ct_maintenance_runs_mode')),
    sa.CheckConstraint("status IN ('running', 'complete', 'failed')", name=op.f('ck_ct_maintenance_runs_ck_ct_maintenance_runs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_maintenance_runs'))
    )
    op.create_table('ct_prune_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('candidate_certificates', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('blocked_latest_certificates', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('blocked_missing_summary', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_certificates', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_certificate_hostnames', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_ct_observations', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_prune_runs'))
    )
    op.create_table('ct_stats_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('snapshot_type', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_stats_snapshots'))
    )
    op.create_table('ct_storage_profile_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('settings_hash', sa.Text(), nullable=False),
    sa.Column('storage_profile', sa.Text(), nullable=False),
    sa.Column('cert_storage_mode', sa.Text(), nullable=False),
    sa.Column('hostname_retention_mode', sa.Text(), nullable=False),
    sa.Column('backfill_days', sa.Integer(), nullable=False),
    sa.Column('cert_retention_days', sa.Integer(), nullable=False),
    sa.Column('observation_retention_days', sa.Integer(), nullable=False),
    sa.Column('entry_outcome_retention_days', sa.Integer(), nullable=False),
    sa.Column('metrics_retention_days', sa.Integer(), nullable=False),
    sa.Column('raw_settings_json', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_storage_profile_history')),
    sa.UniqueConstraint('settings_hash', name='uq_ct_storage_profile_history_settings_hash')
    )
    op.create_table('ct_worker_runtime',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('worker_kind', sa.Text(), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=True),
    sa.Column('log_name', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_index', sa.BigInteger(), nullable=True),
    sa.Column('last_successful_index', sa.BigInteger(), nullable=True),
    sa.Column('batch_start_index', sa.BigInteger(), nullable=True),
    sa.Column('batch_end_index', sa.BigInteger(), nullable=True),
    sa.Column('processed_entries', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('stored_certificates', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('duplicate_certificates', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('observed_hostnames', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('new_hostnames', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('parse_errors', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('retryable_errors', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('terminal_errors', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error_type', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_worker_runtime'))
    )
    op.create_table('hostnames',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('registrable_domain', sa.Text(), nullable=False),
    sa.Column('is_wildcard', sa.Boolean(), nullable=False),
    sa.Column('first_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_cert_fingerprint_sha256', sa.Text(), nullable=True),
    sa.Column('latest_cert_not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_cert_not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_cert_issuer_cn', sa.Text(), nullable=True),
    sa.Column('latest_cert_issuer_org', sa.Text(), nullable=True),
    sa.Column('latest_cert_subject_cn', sa.Text(), nullable=True),
    sa.Column('latest_cert_is_precert', sa.Boolean(), nullable=True),
    sa.Column('latest_cert_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hostnames')),
    sa.UniqueConstraint('hostname', name='uq_hostnames_hostname')
    )
    op.create_table('certificate_hostnames',
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('hostname_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], name=op.f('fk_certificate_hostnames_certificate_id_certificates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostname_id'], ['hostnames.id'], name=op.f('fk_certificate_hostnames_hostname_id_hostnames'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('certificate_id', 'hostname_id', name=op.f('pk_certificate_hostnames'))
    )
    op.create_table('ct_entry_outcomes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('certificate_fingerprint_sha256', sa.Text(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=True),
    sa.Column('raw_entry_hash', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_profile', sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('cert_storage_mode', sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('processed_settings_hash', sa.Text(), server_default=sa.text("'unknown'"), nullable=False),
    sa.CheckConstraint("outcome IN ('parse_error', 'skipped_by_policy', 'stored', 'unsupported_entry_type', 'write_error')", name=op.f('ck_ct_entry_outcomes_outcome')),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_entry_outcomes_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_entry_outcomes')),
    sa.UniqueConstraint('log_source_id', 'log_index', name='uq_ct_entry_outcomes_log_source_id_log_index')
    )
    op.create_table('ct_log_backfill_ranges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('start_index', sa.BigInteger(), nullable=False),
    sa.Column('end_index', sa.BigInteger(), nullable=False),
    sa.Column('next_index', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('range_kind', sa.Text(), server_default=sa.text("'backfill'"), nullable=False),
    sa.Column('repair_for_finding_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reconcile_for_settings_hash', sa.Text(), nullable=True),
    sa.Column('reconcile_target_settings_hash', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_backfill_ranges_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repair_for_finding_id'], ['ct_audit_findings.id'], name='fk_ct_log_backfill_ranges_repair_for_finding_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_backfill_ranges')),
    sa.UniqueConstraint('log_source_id', 'start_index', 'end_index', name='uq_ct_log_backfill_ranges_log_source_start_end')
    )
    op.create_table('ct_log_backfill_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checkpoint_index', sa.BigInteger(), nullable=True),
    sa.Column('backfill_start_index', sa.BigInteger(), nullable=True),
    sa.Column('backfill_end_index', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error_type', sa.Text(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limited_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retryable_error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('terminal_error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('observed_oldest_not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_extended_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_backfill_state_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_backfill_state')),
    sa.UniqueConstraint('log_source_id', name=op.f('uq_ct_log_backfill_state_log_source_id'))
    )
    op.create_table('ct_log_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], name=op.f('fk_ct_log_observations_certificate_id_certificates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_observations_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_observations')),
    sa.UniqueConstraint('log_source_id', 'log_index', name='uq_ct_log_observations_log_source_id_log_index')
    )
    op.create_table('ct_log_runtime_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('tree_size', sa.Integer(), nullable=True),
    sa.Column('sth_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.Text(), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('current_batch_size', sa.Integer(), nullable=False),
    sa.Column('learned_max_batch_size', sa.Integer(), nullable=False),
    sa.Column('backoff_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_429_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_runtime_state_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_runtime_state')),
    sa.UniqueConstraint('log_source_id', name=op.f('uq_ct_log_runtime_state_log_source_id'))
    )
    op.create_table('ct_log_tail_cursors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('next_index', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_tail_cursors_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_tail_cursors')),
    sa.UniqueConstraint('log_source_id', name=op.f('uq_ct_log_tail_cursors_log_source_id'))
    )
    op.create_table('ct_log_tail_leases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_tail_leases_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_tail_leases')),
    sa.UniqueConstraint('log_source_id', name=op.f('uq_ct_log_tail_leases_log_source_id'))
    )
    op.create_table('ingestion_errors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ingestion_errors_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_errors'))
    )
    op.create_table('ingestion_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('entries_fetched', sa.BigInteger(), nullable=False),
    sa.Column('entries_parsed', sa.BigInteger(), nullable=False),
    sa.Column('certs_upserted', sa.BigInteger(), nullable=False),
    sa.Column('hostnames_upserted', sa.BigInteger(), nullable=False),
    sa.Column('new_unique_certificates', sa.BigInteger(), nullable=False),
    sa.Column('duplicate_certificates', sa.BigInteger(), nullable=False),
    sa.Column('new_unique_hostnames', sa.BigInteger(), nullable=False),
    sa.Column('known_hostnames', sa.BigInteger(), nullable=False),
    sa.Column('retryable_errors', sa.BigInteger(), nullable=False),
    sa.Column('terminal_entry_errors', sa.BigInteger(), nullable=False),
    sa.Column('parse_errors', sa.Integer(), nullable=False),
    sa.Column('http_429_count', sa.Integer(), nullable=False),
    sa.Column('http_5xx_count', sa.Integer(), nullable=False),
    sa.Column('throughput_entries_per_sec', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ingestion_metrics_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_metrics'))
    )
    op.create_table('ct_audit_findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=True),
    sa.Column('finding_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('range_id', sa.UUID(), nullable=True),
    sa.Column('start_index', sa.BigInteger(), nullable=True),
    sa.Column('end_index', sa.BigInteger(), nullable=True),
    sa.Column('missing_count', sa.Integer(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repair_action', sa.Text(), nullable=True),
    sa.Column('repair_details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repair_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repair_attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_audit_findings_log_source_id_ct_log_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['range_id'], ['ct_log_backfill_ranges.id'], name=op.f('fk_ct_audit_findings_range_id_ct_log_backfill_ranges'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_audit_findings'))
    )
    # ### end Alembic commands ###

    # GIN trigram index for fast hostname prefix/substring searches.
    op.create_index(
        "ix_hostnames_hostname_trgm",
        "hostnames",
        [sa.text("hostname gin_trgm_ops")],
        postgresql_using="gin",
    )
    op.execute("ANALYZE hostnames")

    # Deferred circular FK: ct_log_backfill_ranges -> ct_audit_findings.
    # use_alter=True in the ORM model so it must be created after both tables.
    op.create_foreign_key(
        "fk_ct_log_backfill_ranges_repair_for_finding_id",
        "ct_log_backfill_ranges",
        "ct_audit_findings",
        ["repair_for_finding_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Performance indexes from the original migration set.
    _PERF_INDEXES = [
        ("idx_ct_log_backfill_ranges_status", "ct_log_backfill_ranges", ["status"]),
        (
            "idx_ct_log_backfill_ranges_log_status",
            "ct_log_backfill_ranges",
            ["log_source_id", "status"],
        ),
        (
            "idx_ct_log_backfill_ranges_status_heartbeat",
            "ct_log_backfill_ranges",
            ["status", "heartbeat_at"],
        ),
        (
            "idx_ct_entry_outcomes_log_index",
            "ct_entry_outcomes",
            ["log_source_id", "log_index"],
        ),
        ("idx_ct_entry_outcomes_outcome", "ct_entry_outcomes", ["outcome"]),
        ("idx_ct_entry_outcomes_processed_at", "ct_entry_outcomes", ["first_seen_at"]),
        ("idx_ct_log_observations_observed_at", "ct_log_observations", ["observed_at"]),
        (
            "idx_ct_log_observations_log_index",
            "ct_log_observations",
            ["log_source_id", "log_index"],
        ),
        ("idx_ingestion_metrics_snapshot_at", "ingestion_metrics", ["snapshot_at"]),
        (
            "idx_ct_audit_findings_status_severity",
            "ct_audit_findings",
            ["status", "severity"],
        ),
    ]
    for idx_name, table_name, columns in _PERF_INDEXES:
        op.create_index(idx_name, table_name, columns)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _PERF_INDEXES = [
        "idx_ct_log_backfill_ranges_status",
        "idx_ct_log_backfill_ranges_log_status",
        "idx_ct_log_backfill_ranges_status_heartbeat",
        "idx_ct_entry_outcomes_log_index",
        "idx_ct_entry_outcomes_outcome",
        "idx_ct_entry_outcomes_processed_at",
        "idx_ct_log_observations_observed_at",
        "idx_ct_log_observations_log_index",
        "idx_ingestion_metrics_snapshot_at",
        "idx_ct_audit_findings_status_severity",
    ]
    for idx_name in _PERF_INDEXES:
        op.drop_index(idx_name, if_exists=True)
    op.drop_index("ix_hostnames_hostname_trgm", table_name="hostnames", if_exists=True)
    op.drop_constraint(
        "fk_ct_log_backfill_ranges_repair_for_finding_id",
        "ct_log_backfill_ranges",
        type_="foreignkey",
    )
    op.drop_table('ct_audit_findings')
    op.drop_table('ingestion_metrics')
    op.drop_table('ingestion_errors')
    op.drop_table('ct_log_tail_leases')
    op.drop_table('ct_log_tail_cursors')
    op.drop_table('ct_log_runtime_state')
    op.drop_table('ct_log_observations')
    op.drop_table('ct_log_backfill_state')
    op.drop_table('ct_log_backfill_ranges')
    op.drop_table('ct_entry_outcomes')
    op.drop_table('certificate_hostnames')
    op.drop_table('hostnames')
    op.drop_table('ct_worker_runtime')
    op.drop_table('ct_storage_profile_history')
    op.drop_table('ct_stats_snapshots')
    op.drop_table('ct_prune_runs')
    op.drop_table('ct_maintenance_runs')
    op.drop_table('ct_log_sources')
    op.drop_table('ct_instance_settings')
    op.drop_table('ct_db_contention_state')
    op.drop_table('certificates')
    # ### end Alembic commands ###
