"""initial_schema

Revision ID: dab4963f165e
Revises: 
Create Date: 2026-05-03 20:33:06.392443

"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dab4963f165e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fingerprint_sha256', sa.Text(), nullable=False),
    sa.Column('spki_sha256', sa.Text(), nullable=False),
    sa.Column('serial_number', sa.Text(), nullable=False),
    sa.Column('issuer_dn', sa.Text(), nullable=False),
    sa.Column('issuer_common_name', sa.Text(), nullable=True),
    sa.Column('issuer_organization', sa.Text(), nullable=True),
    sa.Column('subject_dn', sa.Text(), nullable=False),
    sa.Column('subject_common_name', sa.Text(), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_algorithm_oid', sa.Text(), nullable=False),
    sa.Column('signature_algorithm_name', sa.Text(), nullable=False),
    sa.Column('public_key_algorithm_oid', sa.Text(), nullable=False),
    sa.Column('public_key_algorithm_name', sa.Text(), nullable=False),
    sa.Column('public_key_bits_or_curve', sa.Text(), nullable=True),
    sa.Column('is_precertificate', sa.Boolean(), nullable=False),
    sa.Column('is_wildcard_present', sa.Boolean(), nullable=False),
    sa.Column('san_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates')),
    sa.UniqueConstraint('fingerprint_sha256', name='uq_certificates_fingerprint_sha256')
    )
    op.create_table('ct_log_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_id_b64', sa.Text(), nullable=False),
    sa.Column('operator_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('public_key_b64', sa.Text(), nullable=False),
    sa.Column('log_state', sa.Text(), nullable=False),
    sa.Column('temporal_shard_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temporal_shard_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_eligible_for_tail', sa.Boolean(), nullable=False),
    sa.Column('is_eligible_for_backfill', sa.Boolean(), nullable=False),
    sa.Column('source_list', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_sources')),
    sa.UniqueConstraint('log_id_b64', name='uq_ct_log_sources_log_id_b64'),
    sa.UniqueConstraint('url', name='uq_ct_log_sources_url')
    )
    op.create_table('hostnames',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('registrable_domain', sa.Text(), nullable=False),
    sa.Column('is_wildcard', sa.Boolean(), nullable=False),
    sa.Column('first_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_ct', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_cert_fingerprint_sha256', sa.Text(), nullable=True),
    sa.Column('latest_cert_not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_cert_not_after', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hostnames')),
    sa.UniqueConstraint('hostname', name='uq_hostnames_hostname')
    )
    op.create_table('certificate_hostnames',
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('hostname_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], name=op.f('fk_certificate_hostnames_certificate_id_certificates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostname_id'], ['hostnames.id'], name=op.f('fk_certificate_hostnames_hostname_id_hostnames'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('certificate_id', 'hostname_id', name=op.f('pk_certificate_hostnames'))
    )
    op.create_table('ct_log_backfill_ranges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('start_index', sa.BigInteger(), nullable=False),
    sa.Column('end_index', sa.BigInteger(), nullable=False),
    sa.Column('next_index', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('claimed_by', sa.Text(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_backfill_ranges_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_backfill_ranges')),
    sa.UniqueConstraint('log_source_id', 'start_index', 'end_index', name='uq_ct_log_backfill_ranges_log_source_start_end')
    )
    op.create_table('ct_log_observations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=False),
    sa.Column('certificate_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificates.id'], name=op.f('fk_ct_log_observations_certificate_id_certificates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_observations_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_observations')),
    sa.UniqueConstraint('log_source_id', 'log_index', name='uq_ct_log_observations_log_source_id_log_index')
    )
    op.create_table('ct_log_runtime_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('tree_size', sa.Integer(), nullable=True),
    sa.Column('sth_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.Text(), nullable=False),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('current_batch_size', sa.Integer(), nullable=False),
    sa.Column('learned_max_batch_size', sa.Integer(), nullable=False),
    sa.Column('backoff_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_429_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_runtime_state_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_runtime_state')),
    sa.UniqueConstraint('log_source_id', name=op.f('uq_ct_log_runtime_state_log_source_id'))
    )
    op.create_table('ct_log_tail_cursors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('next_index', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ct_log_tail_cursors_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ct_log_tail_cursors')),
    sa.UniqueConstraint('log_source_id', name=op.f('uq_ct_log_tail_cursors_log_source_id'))
    )
    op.create_table('ingestion_errors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('log_index', sa.BigInteger(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ingestion_errors_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_errors'))
    )
    op.create_table('ingestion_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('log_source_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('entries_fetched', sa.BigInteger(), nullable=False),
    sa.Column('entries_parsed', sa.BigInteger(), nullable=False),
    sa.Column('certs_upserted', sa.BigInteger(), nullable=False),
    sa.Column('hostnames_upserted', sa.BigInteger(), nullable=False),
    sa.Column('parse_errors', sa.Integer(), nullable=False),
    sa.Column('http_429_count', sa.Integer(), nullable=False),
    sa.Column('http_5xx_count', sa.Integer(), nullable=False),
    sa.Column('throughput_entries_per_sec', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['log_source_id'], ['ct_log_sources.id'], name=op.f('fk_ingestion_metrics_log_source_id_ct_log_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_metrics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_metrics')
    op.drop_table('ingestion_errors')
    op.drop_table('ct_log_tail_cursors')
    op.drop_table('ct_log_runtime_state')
    op.drop_table('ct_log_observations')
    op.drop_table('ct_log_backfill_ranges')
    op.drop_table('certificate_hostnames')
    op.drop_table('hostnames')
    op.drop_table('ct_log_sources')
    op.drop_table('certificates')
    # ### end Alembic commands ###
